config/routes.rb
Rails.application.routes.draw do

  get 'user_genres/new'

  devise_for :users
  root to: "pages#home"
  get "css_template", to: "pages#css_template"
  get "about", to: "pages#about"
  get "start_chat", to: "users#chatroom"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :user_instruments, only: %i[new create destroy]
  resources :user_genres, only: %i[new create destroy]

  # Defines the root path route ("/")
  # root "articles#index"
  get "profile", to: "users#my_profile"
  get "error", to: "pages#error"

  resources :users do
    resources :genres, only: %i[index show destroy]
  end

  resources :chatrooms do
    resources :messages
  end
  resources :instruments, only: %i[index show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Don't display current user in chatroom
  scope :all_except, ->(user) { where.not(id: user) }
  # Automatically add user to chatroom when they join
  after_create_commit { broadcast_append_to 'users' }

  has_many :user_instruments, dependent: :destroy
  has_many :user_genres, dependent: :destroy
  has_many :messages
  has_many :instruments, through: :user_instruments
  has_many :genres, through: :user_genres
  has_many :chatroom_users
  has_many :instruments, through: :user_instruments

  has_one_attached :photo
  has_one_attached :background



  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :city ],
    using: {
      tsearch: { prefix: true }
    }

  # pg_search_scope :global_search,
  #   against: [:city],
  #   associated_against: {
  #     instrument: [:name]
  #   },
  #   using: {
  #     tsearch: { prefix: true }
  #   }

  def full_name
    return if first_name.blank?

    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def age
    return if dob.blank?
    ((Time.zone.now - dob.to_time) / 1.year.seconds).floor
  end

  def updated_ability
    return if ability.blank?

    if ability == 0
      return "Beginner"
    elsif ability == 1
      return "Intermediate"
    elsif ability == 2
      return "Advanced"
    elsif ability == 3
      return "Expert"
    end
  end

  def online?
    return if last_login_at.nil?

    last_login_at > 30.minutes.ago
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  def index
    if params[:query].present?
      sql_query = "city ILIKE :query"
      @users = policy_scope(User).where(sql_query, query: "%#{params[:query]}%").where.not(id: current_user)
    else
      @users = policy_scope(User).where.not(id: current_user)
      # @users = policy_scope(User).all
    end
  end

  def show
    @user = User.find(params[:id])
    authorize(@user)
  end

  def chatroom
    # Get user the current user wants to chat with
    if params[:id]
      @user = User.find(params[:id])
    else
      # If user clicks on messages tab then find a user who they have already started a chat with
      user_chatroom = ChatroomUser.where(chatroom_id: current_user.chatroom_users.first.chatroom_id)
      @user = user_chatroom.where.not(user_id: current_user.id).first.user
    end

    @users = User.new
    skip_authorization

    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all
    @chatroom_name = get_name(@user, current_user)
    @single_room = Chatroom.where(name: @chatroom_name).first ||
                   Chatroom.create_private_room([@user, current_user], @chatroom_name)

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    @users = User.all_except(current_user)

    render 'chatrooms/index'
  end

  def edit
    @user = User.find(params[:id])
    authorize(@user)
  end

  def update
    @user = User.find(params[:id])

    authorize(@user)

    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def my_profile
    @user = current_user
    skip_authorization
    @user_instrument = UserInstrument.new(user: current_user)
    @user_genre = UserGenre.new(user: current_user)
  end

  private

  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :postcode, :gender, :dob, :ability, :city, :photo, :background)
  end
end

app/views/users/_user.html.erb
<%# For the chatroom %>

<div>
  <%= link_to user.email, user %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="container login-form d-flex justify-content-center margin-bottom">
  <div class="w-50">
    <div class="card login-form-card">

      <h2>Edit personal details</h2>

      <%= simple_form_for @user do |f| %>
        <%= f.input :first_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
        <%= f.input :last_name,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "email" }%>
        <%= f.input :city,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "email" }%>
        <%= f.input :postcode,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "email" }%>
        <%= f.input :gender,
                    as: :radio_buttons, collection: [['Female'], ['1', 'Male'], ['2', 'Non-binary'], ['3', 'Prefer not to say']], label_method: :second, value_method: :second,
                    required: false,
                    autofocus: true,
                    input_html: { autocomplete: "email" }%>
        <%= f.input :dob,
                    as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 18, discard_day: true, order: [:month, :year],
                    required: false,
                    autofocus: true,
                    input_html: { autocomplete: "email" }%>
        <%= f.input :ability,
                    as: :radio_buttons, collection: [['0', 'Beginner'], ['1', 'Intermediate'], ['2', 'Advanced'], ['3', 'Expert']], label_method: :second, value_method: :first,
                    required: false,
                    autofocus: true,
                    input_html: { autocomplete: "email" }%>
        <%= f.input :photo, as: :file %>
        <%= f.input :background, as: :file %>
        <div class="mt-2">
          <%= f.button :submit, "Update", class: "btn btn-primary text-white"  %>
        </div>
      <% end %>
      <div class="my-4">
        <p><%= link_to 'Back to profile', profile_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="page-margin-top ml-0">
  <% if @users.empty? %>
    <p class="text-center mt-5" style="height: 78vh">
      <strong><%= "There weren't any users matching your search criteria. Please search again" %></strong>
    </p>
  <% else %>
    <div class="row">
      <%= render "shared/cards" %>
    </div>
  <% end %>
</div>

app/views/users/my_profile.html.erb
<div>
  <%= render "shared/banner" %>

  <div style="position:absolute; left: 18%; top: 39%;">

    <%# User profile image %>
    <div class="profile__image">
      <%= render "shared/photo" %>
      <div style="position:absolute; right: 65px; bottom: 1px;">
        <%= link_to edit_user_path(@user) do %>
          <i class="fa-solid fa-user-pen"></i>
        <% end %>
      </div>
    </div>
    <div class="d-none">
      <%= simple_form_for @user do |f| %>
        <%= f.input :photo, as: :file %>
        <div class="form-actions">
          <%= f.button :submit, "Update" %>
        </div>
  <% end %>
    </div>
  </div>

</div>

<div class="margin-top-bottom">
  <div class="profile d-flex mt-5" style="position:relative">
    <div class="row flex-grow-1">
      <div class="col-12 col-lg-6 mb-4">
        <div class="card user-card h-100">
          <div class="card-body">
            <div class="card-title border-bottom">
              <div class="d-flex justify-content-between">
                <h4 class="text-black fw-semibold">Your details</h4>
                <li class="list-unstyled">
                  <%= link_to edit_user_path(@user) do %>
                    <i class="fa-solid fa-user-pen"></i>
                  <% end %>
                </li>
              </div>
            </div>
            <ul class="list-unstyled">
              <li><i class="fa-regular fa-user p-2 icon-width-md"></i>
              <%= @user.first_name.blank? ? "" : @user.full_name %></li>
              <li><i class="fa-solid fa-location-dot p-2 icon-width-md"></i><%= @user.city.blank? ? "" : "#{@user.city}" %></li>
              <li><i class="fa-solid fa-cake-candles p-2 icon-width-md"></i><%= "#{@user.age} years old" %></li>
              <li><i class="fa-sharp fa-solid fa-building-columns p-2 icon-width-md"></i><%= "#{@user.updated_ability}" %></li>
            </ul>
            <h5 class="text-black fw-semibold">About Me</h5>
            <p> <%= current_user.bio %> </p>

          </div>
        </div>
      </div>
      <div class="col-6 col-lg-3 mb-4">
        <div class="card user-card h-100">
          <div class="card-body">
            <div class="card-title border-bottom">
                <h4 class="text-black fw-semibold">Instruments</h4>
            </div>
            <% if @user.user_instruments.empty? %>
              <p>Instruments yet to be added</p>
            <% else %>
              <ul class="list-unstyled">
                <% @user.user_instruments.each do |user_instrument| %>
                  <li class="pt-1">
                    <%= user_instrument.instrument.name.capitalize %>
                    <%= link_to user_instrument_path(user_instrument), data: { "turbo-method": :delete } do %>
                      <i class="fa-regular fa-square-minus p-1 ml-5"></i>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          <div style="position:absolute; bottom: 20px ;" >
            <%= simple_form_for @user_instrument do |f| %>
              <div class="d-flex align-items-center">
                <%= f.association :instrument,
                  collection: Instrument.where.not(id: current_user.instruments), class: "card-body-title" %>
                <%= f.button :submit, '+', class: 'btn btn-primary ms-2', style: 'padding-top: 6px; margin-top: 12px;' %>
              </div>
            <% end %>
          </div>
          </div>
        </div>
      </div>
            <!--
            <button class="btn btn-primary"><%= link_to 'Add instrument', new_user_instrument_path %></button>
            -->
      <div class="col-6 col-lg-3 mb-4">
        <div class="card user-card h-100">
          <div class="card-body">
            <div class="card-title border-bottom">
                <h4 class="text-black fw-semibold">Genres</h4>
            </div>
            <% if @user.user_genres.empty? %>
              <p>Genres yet to be added</p>
            <% else %>
            <ul class="list-unstyled">
              <% @user.user_genres.each do |user_genre| %>
              <li class="pt-1">
                <%= user_genre.genre.name.capitalize %>
                <%= link_to user_genre_path(user_genre),
                data: { "turbo-method": :delete } do %>
                  <i class="fa-regular fa-square-minus p-1 ml-5"></i>
                <% end %>
              </li>
              <% end %>
            </ul>
            <% end %>
            <div style="position:absolute; bottom: 20px; margin-top-bottom;">
              <%= simple_form_for @user_genre do |f| %>
                <div class="d-flex align-items-center">
                  <%= f.association :genre,
                    collection: Genre.where.not(id: current_user.genres), class: "card-body-title" %>
                  <%= f.button :submit, '+', class: 'btn btn-primary ms-2', style: 'padding-top: 6px; margin-top: 12px;' %>
                </div>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/profile.html.erb
<div class="container">
  <h1>Profile Page</h1>

  <p><%= link_to 'Back to profiles', users_path %></p>


  <h1><%= @user.full_name.capitalize %></h1>
  <p><%= @user.city %></p>
  <p><%= @user.updated_ability.capitalize %></p>
  <% if @user.dob.present? %>
  <p>Age: <%= @user.age %></p>
  <% end %>


  <% if current_user ==  @user %>
    <p><%= link_to 'Edit personal details', edit_user_path(@user) %></p>
  <% end %>


  <h6>Instruments:</h6>

  <% if @user.user_instruments.empty? %>
    <p>It's empty</p>
  <% else %>
    <ul>
      <% @user.user_instruments.each do |user_instrument| %>
        <li>
          <%= user_instrument.instrument.name %>
          <%= link_to 'X', user_instrument_path(user_instrument),
            data: { "turbo-method": :delete } %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if current_user ==  @user %>
    <p><%= link_to 'Add instrument', new_user_instrument_path %></p>
  <% end %>

  <h6>Genres:</h6>
  <ul>
    <% @user.user_genres.each do |user_genre| %>
      <li>
        <%= user_genre.genre.name %>
        <%= link_to 'X', user_genre_path(user_genre),
          data: { "turbo-method": :delete } %>
      </li>
    <% end %>
  </ul>

  <% if current_user ==  @user %>
    <p><%= link_to 'Add a genre', new_user_genre_path %></p>
    <p><%= link_to 'Manage my account', edit_user_registration_path %></p>
  <% end %>

</div>

app/views/users/show.html.erb
  <div>
    <%= render "shared/banner" %>
  </div>
    <div style="position:absolute; left: 28%; top: 39%;">

      <%# User profile image %>
      <div class="profile__image">
         <%= render "shared/photo" %>
      </div>
    </div>


  <div class="container margin-top width-card">
    <div class="mx-auto card user-card h-100 card-margin px-5" style="max-width: 750px;">

        <div class="border-bottom">
          <h1 class="text-black fw-semibold"><%= @user.first_name.blank? ? "" : @user.full_name %></h1>
        </div>

      <ul class="list-unstyled display-content mt-3">
      <div class ="width-content">
        <li class ="right-margin"><i class="fa-solid fa-location-dot p-3 icon-width"></i><%= @user.city.blank? ? "" : "#{@user.city}, Portugal" %></li>
        <li class ="right-margin"><i class="fa-solid fa-cake-candles p-3 icon-width"></i><%= @user.age.blank? ? "" : "#{@user.age} years old" %></li>
        <li class ="right-margin"><i class="fa-solid fa-venus-mars p-3 icon-width"></i><%= @user.gender.blank? ? "" : "#{@user.gender.capitalize}" %></li>
      </div>
      <div class ="width-content">
        <li ><i class="fa-sharp fa-solid fa-building-columns p-3 icon-width"></i><%= "#{@user.updated_ability.capitalize}" %></li>
        <li ><i class="fa-solid fa-guitar p-3 icon-width"></i>
          <% if @user.user_instruments.empty? %>
            User yet to add instrument
          <% else %>
            <% instrument = @user.user_instruments.map do |user_instrument| %>
              <% user_instrument.instrument.name.capitalize %>
            <% end %>
              <%= instrument.to_sentence %>
          <% end %>
        </li>
        <li class="ml-1 "><i class="fa-solid fa-music p-3 icon-width"></i>
          <% if @user.user_genres.empty? %>
            User yet to add genre
          <% else %>
            <% genre = @user.user_genres.map do |user_genre| %>
              <% user_genre.genre.name.capitalize %>
            <% end %>
              <%= genre.to_sentence %>
          <% end %>
        </li>
      </div>
      </ul>
      <div>
        <h5 class="card-body-title fw-semibold text-black"><%= "About #{@user.first_name.capitalize}"  %></h5>
        <p><%= @user.bio %></p>

        <div class="d-flex justify-content-between align-items-center mt-3">
          <%= link_to "Message", start_chat_path(id: @user), class:"btn btn-primary mt-2" %>

          <%# Show music player if user is Will or Pedro %>
          <div>
            <% if @user == User.find_by_email("will@gmail.com") %>
              <audio
                controls
                src="https://res.cloudinary.com/ds9cwrw2s/video/upload/v1662634748/will-guitar_lnc0qe.mp3">
                    Your browser does not support the
                    <code>audio</code> element.
              </audio>
            <% elsif @user == User.find_by_email("pedro@gmail.com") %>
              <audio
                controls
                src="https://res.cloudinary.com/ds9cwrw2s/video/upload/v1662634759/pedro-guitar_uaonwc.mp3">
                    Your browser does not support the
                    <code>audio</code> element.
              </audio>
              <% end %>

          </div>
        </div>

      </div>
      <%= link_to users_path do %>
        <a onclick="history.back()">
        <i class="fa-solid fa-arrow-left mt-3"></i>
        </a>
      <% end %>
    </div>



  </div>