config/routes.rb
Rails.application.routes.draw do

  get 'user_genres/new'

  devise_for :users
  root to: "pages#home"
  get "css_template", to: "pages#css_template"
  get "about", to: "pages#about"
  get "start_chat", to: "users#chatroom"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :user_instruments, only: %i[new create destroy]
  resources :user_genres, only: %i[new create destroy]

  # Defines the root path route ("/")
  # root "articles#index"
  get "profile", to: "users#my_profile"
  get "error", to: "pages#error"

  resources :users do
    resources :genres, only: %i[index show destroy]
  end

  resources :chatrooms do
    resources :messages
  end
  resources :instruments, only: %i[index show]
end

app/views/shared/_banner.html.erb
  <% if @user.background.attached? %>
    <div style="height: 50vh; background-position: center; background-size: cover;   background-repeat: no-repeat; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @user.background.key, crop: :fill %>')"></div>
  <% else %>
    <div style="height: 50vh; background: center; background-size: cover;   background-repeat: no-repeat; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @user.banner_img_url %>')"></div>
  <% end %>

app/views/shared/_cards.html.erb
    <% @users.each do |user| %>
    <div class="col-12 col-md-6 col-lg-3 ">
      <%= link_to user_path(user) do %>
      <div class="card card-jamseeds mb-5">
          <% if user.background.attached? %>
            <div class="card-background" style="background-position: center; background-size: cover;   background-repeat: no-repeat; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path user.background.key, crop: :fill %>')"></div>
          <% else %>
            <div class="card-background" style="background: center; background-size: cover;   background-repeat: no-repeat; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= user.banner_img_url %>')"></div>
          <% end %>
        <div class="card-body">
          <div class="d-flex align-items-center mb-3">
            <% if user.photo.attached? %>
              <%= cl_image_tag user.photo.key, gravity: "face", crop: :thumb, class: "card-body__image rounded-circle border-2 border #{user.online? ? 'border green-border' : ''}" %>
            <% else %>
              <img class="card-body__image <%= user.online? ? 'border green-border' : '' %>" src="<%= user.profile_img_url %>" alt="">
            <% end %>
            <div>
              <h2 class="card-title card-body-title mt-2">  <%= user.first_name %></h2>
              <p class="card-text"> <%= "#{user.city}, Portugal" %></p>
            </div>
          </div>
          <div class="card-body__details">
            <div>
              <div>
                <i class="fa-solid fa-guitar icon-width-sm"></i>
                <% if user.user_instruments.empty? %>
                  <span class="card-body__details">Instruments yet to be added</span>
                <% else %>
                  <%= user.instruments.first(3).pluck(:name).map(&:capitalize).to_sentence %>
                <% end %>
              </div>
              <div>
                <i class="fa-solid fa-music icon-width-sm"></i>
                  <% if user.user_genres.empty? %>
                    <span class="card-body__details">Genres yet to be added</span>
                  <% else %>
                    <% genre = [] %>
                    <% user.genres.first(3).each do |user_genre| %>
                      <span class="card-body__details"><% genre << " #{user_genre.name.capitalize}" %>
                    <% end %>
                    <%= genre.to_sentence %>
                    </span>
                  <% end %>
              </div>
              <div>
                <i class="fa-solid fa-building-columns icon-width-sm"></i>
                  <span><%= user.updated_ability %></span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-5">
  <div>
    <i class="fa-solid fa-image p-3"></i>
    <i class="fa-brands fa-github p-3"></i>
    <i class="fa-brands fa-medium p-3"></i>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-jamseeds border-bottom">

  <div class="container">
    <div>
      <%= link_to user_signed_in? ? users_path : root_path do %>
        <h2 class="fw-bold mb-0 navbar-title-color">
          Jamseed
        </h2>
      <% end %>
    </div>
    <div>
      <%= form_with url: users_path, method: :get, class: "search-bar" do %>
        <ul class="navbar-nav me-auto">
          <%= text_field_tag :query, params[:query], class: "form-control search", placeholder: "Search by City" %>
          <%= submit_tag "Search", class: "btn btn-secondary" %>
        </ul>
      <% end %>
    </div>
      <%# Navbar %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav me-auto align-items-center">
          <li class="nav-item" id="navbarDropdown" data-bs-toggle="dropdown" style="cursor: pointer;">
            <i class="fa fa-bars pe-3 text-white"></i>
              <li class="nav-item dropdown">

            <%# User profile photo %>
            <% if current_user.photo.key %>
              <%= cl_image_tag current_user.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag current_user.profile_img_url, class: "avatar" %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# <%= link_to "Find Musicians", users_path, class: "dropdown-item" %>
              <% unless current_user.chatroom_users.length == 0 %>
                <%= link_to "Messages", start_chat_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "My Profile", profile_path, class: "dropdown-item" %>
              <%= link_to 'Manage my account', edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
        <% else %>
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-white" %>
            </li>
          </ul>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_photo.html.erb
<% if @user.photo.attached? %>
  <%= cl_image_tag @user.photo.key, width: 150, height: 150, gravity: "face", crop: :thumb, class: "rounded-circle border-2 border card-body__imagelg #{@user.online? ? 'border green-border' : ''}" %>
<% else %>
  <img class="card-body__imagelg <%= @user.online? ? 'border green-border' : '' %>" src="<%= @user.profile_img_url %>" alt="">
<% end %>

app/views/shared/_search.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Artist Search</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <%= form_with url: users_path, method: :get, class: "search-bar" do %>

                  <%= text_field_tag :query, params[:query], class: "form-control search", placeholder: "Search by City" %>
                  <%= text_field_tag :query, params[:query], class: "form-control search", placeholder: "Search by ability" %>
                  <%= submit_tag "Search", class: "btn btn-secondary" %>

                <% end %>
              </div>
            </div>
          </div>
        </div>