config/routes.rb
Rails.application.routes.draw do

  get 'user_genres/new'

  devise_for :users
  root to: "pages#home"
  get "css_template", to: "pages#css_template"
  get "about", to: "pages#about"
  get "start_chat", to: "users#chatroom"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :user_instruments, only: %i[new create destroy]
  resources :user_genres, only: %i[new create destroy]

  # Defines the root path route ("/")
  # root "articles#index"
  get "profile", to: "users#my_profile"
  get "error", to: "pages#error"

  resources :users do
    resources :genres, only: %i[index show destroy]
  end

  resources :chatrooms do
    resources :messages
  end
  resources :instruments, only: %i[index show]
end

app/views/pages/css_template.html.erb
<div class="container">
  <br>

  <h1>Headers, Paragraphs & Links</h1>
  <div>
    <hr>
    <h1>Header H1</h1>
    <h2>Header H2</h2>
    <h3>Header H3</h3>
    <h4>Header H4</h4>
    <h5>Header H5</h5>
    <h6>Header H6</h6>
    <p></p>
    <p>This is a paragraph</p>
    <a href="#">This is a link</a>
    <br>
    <br>
    <br>
  </div>

  <h1>Buttons</h1>
  <div>
    <hr>
    <div class="btn btn-primary">Primary Button</div>
    <div class="btn btn-secondary">Secondary Button</div>
    <br><br><br>
    <h1>User Card</h1>
    <hr>
  </div>

  <%# User profile card %>
  <%= link_to css_template_path, class: "card-link" do %>
    <div class="card-profile-small">

      <div class="card-bg">
        <div>
          <img src="https://image.shutterstock.com/image-photo/portrait-happy-mature-man-wearing-260nw-732336316.jpg" id="profile-image" alt="User profile image">
          <h5 id="profile-name">Louis Bobby</h5>
          <p>Lisbon, Portugal</p>
          <p>Age: 32</p>
        </div>
      </div>

      <div class="card-body w-100">
          <div>
            <h5 class="card-body-title">Instruments</h5>
            <p class="card-body__details">Vocals&nbsp; Acoustic Guitar&nbsp;  Drums&nbsp;  Bass&nbsp;  Ukulele&nbsp;</p>
            <hr>
          </div>
          <div>
            <h5 class="card-body-title">Genre</h5>
            <p class="card-body__details">Cheese Metal&nbsp;</p>
            <hr>
          </div>
          <div>
            <h5 class="card-body-title">Ability</h5>
            <p class="card-body__details">Expert</p>
        </div>
      </div>
    </div>
  <% end %>

  <br><br><br>

</div>

app/views/pages/home.html.erb
<div class="container">
</div>

<div class="banner banner-image">
  <ul class="d-flex justify-content-end list-unstyled">
    <% unless current_user %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link px-3 py-2 m-3 text-white white-border " %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link p-2 m-3 text-white btn btn-primary btn-box-shadow" %>
      </li>
    <% end %>
  </ul>
  <div class ="d-flex justify-content-between">
    <div class="banner-padding container">
      <h1>Jamseed</h1>
      <p>Bringing <strong>Musicians</strong> together!</p>
      <div class="p-2 text-white btn btn-primary btn-box-shadow">
        <%= link_to 'Search now', users_path, class: "text-white" %>
      </div>
    </div>
  </div>
</div>



<div class="container">

  <div class =" my-5">
    <div class="d-flex justify-content-around">
      <div class="text-center p-3">
        <i class="fa-solid fa-magnifying-glass-location p-5 fa-2xl"></i>
        <h5>Find your people</h5>
      </div>
      <div class="text-center p-3">
        <i class="fa-solid fa-users p-5 fa-2xl"></i>
        <h5>Organise meet ups</h5>
      </div>
      <div class="text-center p-3">
        <i class="fa-solid fa-music p-5 fa-2xl"></i>
        <h5>Play the music you want</h5>
      </div>
    </div>
  </div>


<div class="row">
    <h2 class="mb-4 mt-5 text-black fw-semibold">New Members</h2>
    <%= render "shared/cards" %>

  </div>



  <div class="our-story mt-5 margin-bottom">
    <div class="pr-2 mx-2">
      <h2 class="mb-4 text-black text-black fw-semibold">Our Story</h2>
      <p>Since 2022, we've been on a mission to be the go-to place for musicians in Portugal wanting to join a band and for bands trying to find band members in their area.</p>
      <p>Whether you are a skilled professional with a great track record who wants to play 100 shows a year, or you just picked up an instrument last week, you can be sure to feel right at home on our website. Find band members and bands looking for musicians in your area and grow your musical network quick. </p>
      <div class="btn btn-primary text-white mb-3">
        <%= link_to 'Join today', new_user_path, class: "text-white" %>
      </div>
    </div>
    <div class="text-end ms-3 img-thumbnail rounded img-fluid p-3 ml-2" >
      <%= image_tag("drum.jpg", width: "300") %>
    </div>
  </div>
</div>